version: '3'
services:
  connect-db-cache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - cache

  mysql:
    image: mysql:8.0
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: db
    #   MYSQL_USER: user
    #   MYSQL_PASSWORD: password
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  cache:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
